export const navLink = [
  { id: 1, name: "Bosh sahifa", path: "/" },
  { id: 2, name: " Biz haqimizda", path: "/about" },
  { id: 3, name: "Kategoriyalar", path: "/category" },
  { id: 4, name: "Yangiliklar", path: "/news" },
  { id: 5, name: "Aloqa", path: "/contact" },
];

export const footerImages = [
  {
    id: 1,
    image: "/1.png",
  },
  {
    id: 2,
    image: "/2.png",
  },
  {
    id: 3,
    image: "/3.png",
  },
  {
    id: 4,
    image: "/4.png",
  },
  {
    id: 5,
    image: "/5.png",
  },
  {
    id: 6,
    image: "/6.png",
  },
];
export const cardList = [
  { id: 1, image: "/Icon.png", title: "Become volunteer" },
  { id: 2, image: "/Icon2.png", title: "Call for donation" },
  { id: 1, image: "/Icon1.png", title: "Send donation" },
];
export const footerLinks = [
  { id: 1, name: "About Us" },
  { id: 2, name: "Career" },
  { id: 3, name: "Leadership" },
  { id: 4, name: "FAQ’s" },
  { id: 5, name: "Appointments" },
  { id: 6, name: "Donners" },
  { id: 7, name: "Become Volunteer" },
  { id: 8, name: "Donation History" },
  { id: 9, name: "Donation Failed" },
  { id: 10, name: "404" },
  { id: 11, name: "Coming Soon" },
  { id: 12, name: "Medical facilities" },
];
 export const helpOptions = [
  {
    id: 1,
    title: "Ko‘ngilli bo‘ling",
    description:
      "Siz o‘z vaqtingiz, mahoratingiz va bilimlaringiz bilan saxovatli ishlarga hissa qo‘shishingiz mumkin.",
   image: "/Icon.png"
  },
  {
    id: 2,
    title: "Ehson qilishga chaqirish",
    description:
      "Ehson qilish orqali muhtojlarga yordam berish va jamiyatda yaxshilik tarqatishga yordam bering.",
    image: "/Icon2.png"
  },
  {
    id: 3,
    title: "Ehson yuborish",
    description:
      "Pul yoki boshqa moddiy yordam shakllarini muhtojlarga yetkazib, hayotlarini yaxshilashga hissa qo‘shing.",
   image: "/Icon1.png"
  },
];

export const regions = [
  {
    id: 1,
    title: "Andijon",
    items: [
      "Andijon",
      "Asaka",
      "Baliqchi",
      "Boʻz",
      "Buloqboshi",
      "Izboskan",
      "Jalaquduq",
      "Xoʻjaobod",
      "Qoʻrgʻontepa",
      "Marhamat",
      "Oltinkoʻl",
      "Paxtaobod",
      "Shahrixon",
      "Ulugʻnor",
    ],
  },
  {
    id: 2,
    title: "Buxoro",
    items: [
      "Olot",
      "Buxoro",
      "Gʻijduvon",
      "Jondor",
      "Kogon",
      "Qorakoʻl",
      "Qorovulbozor",
      "Peshku",
      "Romitan",
      "Shofirkon",
      "Vobkent",
    ],
  },
  {
    id: 3,
    title: "Farg'ona",
    items: [
      "Oltiariq",
      "Bagʻdod",
      "Beshariq",
      "Buvayda",
      "Dangʻara",
      "Fargʻona",
      "Furqat",
      "Qoʻshtepa",
      "Quva",
      "Rishton",
      "Soʻx",
      "Toshloq",
      "Uchkoʻprik",
      "Oʻzbekiston",
      "Yozyovon",
      "Quvasoy",
    ],
  },
  {
    id: 4,
    title: "Jizzax",
    items: [
      "Arnasoy",
      "Baxmal",
      "Doʻstlik",
      "Forish",
      "Gʻallaorol",
      "Sharof Rashidov",
      "Mirzachoʻl",
      "Paxtakor",
      "Yangiobod",
      "Zomin",
      "Zafarobod",
      "Zarbdor",
    ],
  },
  {
    id: 5,
    title: "Xorazm",
    items: [
      "Bogʻot",
      "Gurlan",
      "Xonqa",
      "Hazorasp",
      "Xiva",
      "Qoʻshkoʻpir",
      "Shovot",
      "Urganch",
      "Yangiariq",
      "Yangibozor",
      "Tuproqqalʼa",
    ],
  },
  {
    id: 6,
    title: "Namangan",
    items: [
      "Chortoq",
      "Chust",
      "Kosonsoy",
      "Mingbuloq",
      "Namangan",
      "Norin",
      "Pop",
      "Toʻraqoʻrgʻon",
      "Uchqoʻrgʻon",
      "Uychi",
      "Yangiqoʻrgʻon",
    ],
  },
  {
    id: 7,
    title: "Navoiy",
    items: [
      "Konimex",
      "Karmana",
      "Qiziltepa",
      "Xatirchi",
      "Navbahor",
      "Nurota",
      "Tomdi",
      "Uchquduq",
    ],
  },
  {
    id: 8,
    title: "Qashqadaryo",
    items: [
      "Chiroqchi",
      "Dehqonobod",
      "Gʻuzor",
      "Qamashi",
      "Qarshi",
      "Koson",
      "Kasbi",
      "Kitob",
      "Mirishkor",
      "Muborak",
      "Nishon",
      "Shahrisabz",
      "Yakkabogʻ",
      "Koʻkdala",
    ],
  },
  {
    id: 9,
    title: "Qoraqalpog'iston",
    items: [
      "Amudaryo",
      "Beruniy",
      "Chimboy",
      "Ellikqalʼa",
      "Kegeyli",
      "Moʻynoq",
      "Nukus",
      "Qanlikoʻl",
      "Qoʻngʻirot",
      "Qoraoʻzak",
      "Shumanay",
      "Taxtakoʻpir",
      "Toʻrtkoʻl",
      "Xoʻjayli",
      "Taxiatosh",
      "Boʻzatov",
    ],
  },
  {
    id: 10,
    title: "Samarqand",
    items: [
      "Bulungʻur",
      "Ishtixon",
      "Jomboy",
      "Kattaqoʻrgʻon",
      "Qoʻshrabot",
      "Narpay",
      "Nurobod",
      "Oqdaryo",
      "Paxtachi",
      "Payariq",
      "Pastdargʻom",
      "Samarqand",
      "Toyloq",
      "Urgut",
    ],
  },
  {
    id: 11,
    title: "Sirdaryo",
    items: [
      "Oqoltin",
      "Boyovut",
      "Guliston",
      "Xovos",
      "Mirzaobod",
      "Sayxunobod",
      "Sardoba",
      "Sirdaryo",
      "Yangiyer",
      "Shirin",
    ],
  },
  {
    id: 12,
    title: "Surxondaryo",
    items: [
      "Angor",
      "Boysun",
      "Denov",
      "Jarqoʻrgʻon",
      "Qiziriq",
      "Qumqoʻrgʻon",
      "Muzrabot",
      "Oltinsoy",
      "Sariosiyo",
      "Sherobod",
      "Shoʻrchi",
      "Termiz",
      "Uzun",
    ],
  },
  {
    id: 13,
    title: "Toshkent",
    items: [
      "Bekobod",
      "Boʻstonliq",
      "Boʻka",
      "Chinoz",
      "Qibray",
      "Ohangaron",
      "Oqqoʻrgʻon",
      "Parkent",
      "Piskent",
      "Quyi chirchiq",
      "Oʻrta Chirchiq",
      "Yangiyoʻl",
      "Yuqori Chirchiq",
      "Zangiota",
    ],
  },
  {
    id: 14,
    title: "Toshkent shahri",
    items: [
      "Bektemir",
      "Chilonzor",
      "Hamza",
      "Mirobod",
      "Mirzo Ulugʻbek",
      "Sergeli",
      "Shayxontohur",
      "Olmazor",
      "Uchtepa",
      "Yakkasaroy",
      "Yunusobod",
      "Yangihayot",
    ],
  },
];
