export const navLink = [
	{ name: 'Bosh sahifa', path: '/' },
	{ name: ' Biz haqimizda', path: '/about' },
	{ name: 'Kategoriyalar', path: '/category' },
	{ name: 'Yangiliklar', path: '/news' },
	{ name: 'Ariza topshirish', path: '/application' },
]

export const footerImages = [
	{
		id: 1,
		image: '/1.png',
	},
	{
		id: 2,
		image: '/2.png',
	},
	{
		id: 3,
		image: '/3.png',
	},
	{
		id: 4,
		image: '/4.png',
	},
	{
		id: 5,
		image: '/5.png',
	},
	{
		id: 6,
		image: '/6.png',
	},
]
export const cardList = [
	{ id: 1, image: '/Icon.png', title: 'Become volunteer' },
	{ id: 2, image: '/Icon2.png', title: 'Call for donation' },
	{ id: 1, image: '/Icon1.png', title: 'Send donation' },
]
export const footerLinks = [
	{ name: 'About Us' },
	{ name: 'Career' },
	{ name: 'Leadership' },
	{ name: 'FAQ’s' },
	{ name: 'Appointments' },
	{ name: 'Donners' },
	{ name: 'Become Volunteer' },
	{ name: 'Donation History' },
	{ name: 'Donation Failed' },
	{ name: '404' },
	{ name: 'Coming Soon' },
	{ name: 'Medical facilities' },
]
export const donationCards = [
	{
		image: '/help3.png',
		title: 'Old Education Needs For All.',
		description:
			'Lorem Ipsum is simply dummy text of the industry’s since the unknown.',
		name: 'Adam',
	},
	{
		image: '/help3.png',
		goal: '$3000',
		rise: '$2500',
		toGo: '$500',
		title: 'Old Education Needs For All',
		description:
			'Lorem Ipsum is simply dummy text of the industry’s since the unknown.',
		name: 'Adam',
	},
	{
		image: '/help3.png',
		title: 'Needs For Change The World.',
		description:
			'Lorem Ipsum is simply dummy text of the industry’s since the unknown.',
		name: 'Adam',
	},
	{
		image: '/help3.png',
		title: 'Old Education Needs For All',
		description:
			'Lorem Ipsum is simply dummy text of the industry’s since the unknown.',
		name: 'Adam',
	},
]

export const regions = [
	{
		id: 1,
		title: 'Andijon',
		items: [
			'Andijon',
			'Asaka',
			'Baliqchi',
			'Boʻz',
			'Buloqboshi',
			'Izboskan',
			'Jalaquduq',
			'Xoʻjaobod',
			'Qoʻrgʻontepa',
			'Marhamat',
			'Oltinkoʻl',
			'Paxtaobod',
			'Shahrixon',
			'Ulugʻnor',
		],
	},
	{
		id: 2,
		title: 'Buxoro',
		items: [
			'Olot',
			'Buxoro',
			'Gʻijduvon',
			'Jondor',
			'Kogon',
			'Qorakoʻl',
			'Qorovulbozor',
			'Peshku',
			'Romitan',
			'Shofirkon',
			'Vobkent',
		],
	},
	{
		id: 3,
		title: "Farg'ona",
		items: [
			'Oltiariq',
			'Bagʻdod',
			'Beshariq',
			'Buvayda',
			'Dangʻara',
			'Fargʻona',
			'Furqat',
			'Qoʻshtepa',
			'Quva',
			'Rishton',
			'Soʻx',
			'Toshloq',
			'Uchkoʻprik',
			'Oʻzbekiston',
			'Yozyovon',
			'Quvasoy',
		],
	},
	{
		id: 4,
		title: 'Jizzax',
		items: [
			'Arnasoy',
			'Baxmal',
			'Doʻstlik',
			'Forish',
			'Gʻallaorol',
			'Sharof Rashidov',
			'Mirzachoʻl',
			'Paxtakor',
			'Yangiobod',
			'Zomin',
			'Zafarobod',
			'Zarbdor',
		],
	},
	{
		id: 5,
		title: 'Xorazm',
		items: [
			'Bogʻot',
			'Gurlan',
			'Xonqa',
			'Hazorasp',
			'Xiva',
			'Qoʻshkoʻpir',
			'Shovot',
			'Urganch',
			'Yangiariq',
			'Yangibozor',
			'Tuproqqalʼa',
		],
	},
	{
		id: 6,
		title: 'Namangan',
		items: [
			'Chortoq',
			'Chust',
			'Kosonsoy',
			'Mingbuloq',
			'Namangan',
			'Norin',
			'Pop',
			'Toʻraqoʻrgʻon',
			'Uchqoʻrgʻon',
			'Uychi',
			'Yangiqoʻrgʻon',
		],
	},
	{
		id: 7,
		title: 'Navoiy',
		items: [
			'Konimex',
			'Karmana',
			'Qiziltepa',
			'Xatirchi',
			'Navbahor',
			'Nurota',
			'Tomdi',
			'Uchquduq',
		],
	},
	{
		id: 8,
		title: 'Qashqadaryo',
		items: [
			'Chiroqchi',
			'Dehqonobod',
			'Gʻuzor',
			'Qamashi',
			'Qarshi',
			'Koson',
			'Kasbi',
			'Kitob',
			'Mirishkor',
			'Muborak',
			'Nishon',
			'Shahrisabz',
			'Yakkabogʻ',
			'Koʻkdala',
		],
	},
	{
		id: 9,
		title: "Qoraqalpog'iston",
		items: [
			'Amudaryo',
			'Beruniy',
			'Chimboy',
			'Ellikqalʼa',
			'Kegeyli',
			'Moʻynoq',
			'Nukus',
			'Qanlikoʻl',
			'Qoʻngʻirot',
			'Qoraoʻzak',
			'Shumanay',
			'Taxtakoʻpir',
			'Toʻrtkoʻl',
			'Xoʻjayli',
			'Taxiatosh',
			'Boʻzatov',
		],
	},
	{
		id: 10,
		title: 'Samarqand',
		items: [
			'Bulungʻur',
			'Ishtixon',
			'Jomboy',
			'Kattaqoʻrgʻon',
			'Qoʻshrabot',
			'Narpay',
			'Nurobod',
			'Oqdaryo',
			'Paxtachi',
			'Payariq',
			'Pastdargʻom',
			'Samarqand',
			'Toyloq',
			'Urgut',
		],
	},
	{
		id: 11,
		title: 'Sirdaryo',
		items: [
			'Oqoltin',
			'Boyovut',
			'Guliston',
			'Xovos',
			'Mirzaobod',
			'Sayxunobod',
			'Sardoba',
			'Sirdaryo',
			'Yangiyer',
			'Shirin',
			'Guliston',
		],
	},
	{
		id: 12,
		title: 'Surxondaryo',
		items: [
			'Angor',
			'Boysun',
			'Denov',
			'Jarqoʻrgʻon',
			'Qiziriq',
			'Qumqoʻrgʻon',
			'Muzrabot',
			'Oltinsoy',
			'Sariosiyo',
			'Sherobod',
			'Shoʻrchi',
			'Termiz',
			'Uzun',
		],
	},
	{
		id: 13,
		title: 'Toshkent',
		items: [
			'Bekobod',
			'Boʻstonliq',
			'Boʻka',
			'Chinoz',
			'Qibray',
			'Ohangaron',
			'Oqqoʻrgʻon',
			'Parkent',
			'Piskent',
			'Quyi chirchiq',
			'Oʻrta Chirchiq',
			'Yangiyoʻl',
			'Yuqori Chirchiq',
			'Zangiota',
		],
	},
	{
		id: 14,
		title: 'Toshkent shahri',
		items: [
			'Bektemir',
			'Chilonzor',
			'Hamza',
			'Mirobod',
			'Mirzo Ulugʻbek',
			'Sergeli',
			'Shayxontohur',
			'Olmazor',
			'Uchtepa',
			'Yakkasaroy',
			'Yunusobod',
			'Yangihayot',
		],
	},
]
