import type { Metadata } from "next";
import { Crete_Round, Work_Sans } from "next/font/google";
import "./globals.css";

import { ChildProps } from "@/types";
import Navbar from "./(root)/components/navbar";
import Footer from "./(root)/components/footer";


const creteRound = Crete_Round({
  weight: ['400'],
  variable: "--font-creteRound",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  weight: ['500','600'],
  variable: "--font-workSans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({children}:ChildProps) {
  
  return (
    <html lang="en">
      <body
        className={`${creteRound.variable} ${workSans.variable} antialiased overflow-x-hidden`}
      >
        <Navbar />
          <main>
          {children}
          </main> 
          <Footer/>
      </body>
    </html>
  );
}
export default RootLayout